# Generated by Django 6.1.1 on 2026-09-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="amount",
            new_name="quantity",
        ),
    ]
