# Generated by Django 5.2 on 2026-10-07 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_brand_rename_users_order_user_address_product_brand_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Brand",
            new_name="brand",
        ),
    ]
