# Generated by Django 5.2 on 2026-10-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_rename_brand_product_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productvariant",
            name="name",
            field=models.CharField(
                help_text="Example: Size: Medium, Color: Blue", max_length=120
            ),
        ),
    ]
